<?php
$sentryDSN = $block->getDataSourceName();
if ($sentryDSN):
    $customConfiguration = $block->getCustomConfiguration() ?? '{}';
?>

<script src="<?= $block->getViewFileUrl("MageSuite_SentryIo::sentry/bundle.tracing.min.js")?>" data-defer-ignore="true"></script>

<script data-defer-ignore="true">
    const defaultConfig = {
        dsn: "<?=$sentryDSN;?>",
        <?php
        /**
         * Set tracesSampleRate to 1.0 to capture 100%
         * of transactions for performance monitoring.
         * We recommend adjusting this value in production
         */
        ?>
        tracesSampleRate: 1.0,
        sampleRate: 1.0,

        ignoreErrors: [
            'top.GLOBALS',
            'originalCreateNotification',
            'canvas.contentDocument',
            'MyApp_RemoveAllHighlights',
            'http://tt.epicplay.com',
            'Can\'t find variable: ZiteReader',
            'jigsaw is not defined',
            'ComboSearch is not defined',
            'http://loading.retry.widdit.com/',
            'atomicFindClose',
            'fb_xd_fragment',
            'bmi_SafeAddOnload',
            'EBCallBackMessageReceived',
            'conduitPage',
            'Script error.',
            'Script error for'
        ],
        denyUrls: [
            /graph\.facebook\.com/i,
            /connect\.facebook\.net\/en_US\/all\.js/i,
            /eatdifferent\.com\.woopra-ns\.com/i,
            /static\.woopra\.com\/js\/woopra\.js/i,
            /extensions\//i,
            /^chrome:\/\//i,
            /127\.0\.0\.1:4001\/isrunning/i,
            /webappstoolbarba\.texthelp\.com\//i,
            /metrics\.itunes\.apple\.com\.edgesuite\.net\//i
        ],
        release: '<?= $block->getMagentoVersion(); ?>',
    }

    const options = {
        ...defaultConfig,
        ...<?= $customConfiguration; ?>
    }

    Sentry.init(options);
</script>
<?php endif; ?>
