<?php
$sentryDSN = $this->getDataSourceName();
if ($sentryDSN):
    $customConfiguration = $this->getCustomConfiguration() ?? '{}';
?>
    <script>
        require(['jquery', 'raven'], function($, raven) {
            var isLeavingPage = false;

            $(window).on('beforeunload pagehide', function() {
                isLeavingPage = true;
            });
            // Ignore list based off: https://gist.github.com/1878283
            var ravenOptions = $.extend(
                {
                    ignoreErrors: [
                        'top.GLOBALS',
                        'originalCreateNotification',
                        'canvas.contentDocument',
                        'MyApp_RemoveAllHighlights',
                        'http://tt.epicplay.com',
                        'Can\'t find variable: ZiteReader',
                        'jigsaw is not defined',
                        'ComboSearch is not defined',
                        'http://loading.retry.widdit.com/',
                        'atomicFindClose',
                        'fb_xd_fragment',
                        'bmi_SafeAddOnload',
                        'EBCallBackMessageReceived',
                        'conduitPage',
                        'Script error.',
                        'Script error for'
                    ],
                    ignoreUrls: [
                        /graph\.facebook\.com/i,
                        /connect\.facebook\.net\/en_US\/all\.js/i,
                        /eatdifferent\.com\.woopra-ns\.com/i,
                        /static\.woopra\.com\/js\/woopra\.js/i,
                        /extensions\//i,
                        /^chrome:\/\//i,
                        /127\.0\.0\.1:4001\/isrunning/i,
                        /webappstoolbarba\.texthelp\.com\//i,
                        /metrics\.itunes\.apple\.com\.edgesuite\.net\//i
                    ],
                    release: '<?= $this->getMagentoVersion(); ?>',
                    shouldSendCallback: function() {
                        return !isLeavingPage;
                    },
                    dataCallback: function(event) {
                        if (event.transaction) {
                            event.transaction = event.transaction.replace(/\/static\/version[0-9]+\//, "/static/");
                        }
                        return event;
                    }
                },
                <?= $customConfiguration; ?>
            );
            raven.config('<?=$sentryDSN;?>', ravenOptions).install();

            require(['jquery/jquery-storageapi'], function() {
                var scramble = function(data) {
                    return data ? data.replace(/\B[a-z]/g, "*") : '';
                }
                var mageStorage = $.localStorage.get('mage-cache-storage') || {};
                var customerInfo = mageStorage.customer;
                // Sending additional anonymised data along with the error report.
                if (customerInfo && customerInfo.fullname) {
                    raven.setUserContext({
                        name: scramble(customerInfo.fullname)
                    });
                }
                // Sending additional cart contents for potential easier reproduction.
                var cartInfo = mageStorage.cart;
                if (cartInfo && cartInfo.items) {
                    raven.setExtraContext({
                        cart: cartInfo.items.map(function(product) {
                            return {
                                qty: product.qty,
                                sku: product['product_sku']
                            }
                        })
                    });
                }
            });
        });
    </script>
<?php endif; ?>
